hyq:
  # Publish all joint states ----
  # Creates '/joint_states' topic which is passesd to '/namespace/joint_states' in our .launch file
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  lf_haa_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: lf_haa_joint
    pid: {p: 51.3, i: 10.3, d: 1.5, }

  lf_hfe_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: lf_hfe_joint
    pid: {p: 51.3, i: 10.3, d: 1.5, }

  lf_kfe_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: lf_kfe_joint
    pid: {p: 51.3, i: 10.3, d: 1.5, }

  lh_haa_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: lh_haa_joint
    pid: {p: 51.3, i: 10.3, d: 1.5, }

  lh_hfe_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: lh_hfe_joint
    pid: {p: 51.3, i: 10.3, d: 1.5, }

  lh_kfe_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: lh_kfe_joint
    pid: {p: 51.3, i: 10.3, d: 1.5, }

  rf_haa_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rf_haa_joint
    pid: {p: 51.3, i: 10.3, d: 1.5, }

  rf_hfe_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rf_hfe_joint
    pid: {p: 51.3, i: 10.3, d: 1.5, }

  rf_kfe_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rf_kfe_joint
    pid: {p: 51.3, i: 10.3, d: 1.5, }

  rh_haa_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rh_haa_joint
    pid: {p: 51.3, i: 10.3, d: 1.5, }

  rh_hfe_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rh_hfe_joint
    pid: {p: 51.3, i: 10.3, d: 1.5, }

  rh_kfe_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: rh_kfe_joint
    pid: {p: 51.3, i: 10.3, d: 1.5, }


